#!/usr/bin/env python3
"""Rasterize a monospace TTF into a 1bpp Odin bitmap-font table.

Vectra's console fonts are baked into the kernel image; there is no font
loader at boot time. The same table serves ring 3 as sys/libfont, so the
generator takes a package name and `make font` emits both. Regenerate with:

    python3 tools/genfont.py > kernel/drivers/console/font_data.odin
    python3 tools/genfont.py --package libfont > sys/libfont/font_data.odin
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/System/Library/Fonts/Supplemental/PTMono.ttc"
CELL_W, CELL_H = 8, 16
PX = 13          # PTMono at 13px is exactly 8 wide, 12 up + 4 down
BASELINE = 12    # rows from cell top to baseline
THRESHOLD = 96   # coverage above this becomes a lit pixel

FIRST, LAST = 0x20, 0x7E


def render(font, ch):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, BASELINE), ch, font=font, fill=255, anchor="ls")
    rows = []
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if img.getpixel((x, y)) >= THRESHOLD:
                bits |= 0x80 >> x
        rows.append(bits)
    return rows


def main():
    font = ImageFont.truetype(FONT_PATH, PX)
    glyphs = {c: render(font, chr(c)) for c in range(FIRST, LAST + 1)}

    if "--preview" in sys.argv:
        for c in (ord("A"), ord("g"), ord("#"), ord("0"), ord("W")):
            print(f"--- {chr(c)!r} ---")
            for r in glyphs[c]:
                print("".join("#" if r & (0x80 >> x) else "." for x in range(CELL_W)))
        return

    package = "console"
    if "--package" in sys.argv:
        package = sys.argv[sys.argv.index("--package") + 1]

    out = []
    out.append(f"package {package}")
    out.append("")
    out.append("// GENERATED by tools/genfont.py -- do not edit by hand.")
    out.append(f"// Source: {FONT_PATH}")
    out.append(f"// {CELL_W}x{CELL_H} 1bpp cells, one byte per scanline, MSB = leftmost pixel.")
    out.append("")
    out.append(f"FONT_WIDTH  :: {CELL_W}")
    out.append(f"FONT_HEIGHT :: {CELL_H}")
    out.append(f"FONT_FIRST  :: 0x{FIRST:02X}")
    out.append(f"FONT_LAST   :: 0x{LAST:02X}")
    out.append("")
    out.append(f"font_8x16 := [FONT_LAST - FONT_FIRST + 1][FONT_HEIGHT]u8{{")
    for c in range(FIRST, LAST + 1):
        rows = ", ".join(f"0x{b:02x}" for b in glyphs[c])
        label = chr(c) if c != 0x27 else "'"
        out.append(f"\t{{{rows}}}, // 0x{c:02X} {label!r}")
    out.append("}")
    out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
