#!/usr/bin/env python3
"""Rasterize Unicode ranges past ASCII into subfont files and a .font index.

The baked table in sys/libfont holds ASCII, 0x20-0x7E, and the kernel draws
its early-boot log from it before any filesystem is up. Everything past ASCII
is a *file* the system reads at run time -- Plan 9's shape: a .font names rune
ranges and the subfont file each is in, and a subfont holds the 1bpp cells for
its range, the same 8x16 the baked table uses. `sys/libfont/load.odin` reads
them; `docs/DRAW.md` has the format.

The output is checked in under lib/font/, so a build stages it to /lib/font
without rasterizing, the way the baked table is checked in. Regenerate, when
the ranges or the source change, with:

    python3 tools/gensubfont.py

Needs Pillow, which the build does not.
"""
import os
import struct
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/System/Library/Fonts/Supplemental/PTMono.ttc"
CELL_W, CELL_H = 8, 16
PX = 13
BASELINE = 12
THRESHOLD = 96
ASCENT = 12

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "lib", "font")

# The ranges, past ASCII, this system carries. Each is one subfont file. A
# codepoint in a range the source does not draw becomes a blank cell rather
# than a .notdef box, so a range may be contiguous over small gaps.
RANGES = [
    (0x00A0, 0x00FF, "latin1.subf"),   # Latin-1 Supplement: accented letters, symbols
    (0x2010, 0x2027, "punct.subf"),    # dashes, curly quotes, bullet
    (0x2190, 0x2193, "arrows.subf"),   # the four arrows
]

SUBF_MAGIC = 0x46425553  # 'S','U','B','F' little-endian


def render(font, cp):
    """The 1bpp rows for a codepoint, or all-zero when the font draws nothing."""
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    try:
        d.text((0, BASELINE), chr(cp), font=font, fill=255, anchor="ls")
    except Exception:
        return [0] * CELL_H
    rows = []
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if img.getpixel((x, y)) >= THRESHOLD:
                bits |= 0x80 >> x
        rows.append(bits)
    return rows


def write_subfont(font, lo, hi, path):
    with open(path, "wb") as f:
        f.write(struct.pack("<IIIBBH", SUBF_MAGIC, lo, hi, CELL_W, CELL_H, 0))
        for cp in range(lo, hi + 1):
            f.write(bytes(render(font, cp)))


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    font = ImageFont.truetype(FONT_PATH, PX)
    for lo, hi, name in RANGES:
        write_subfont(font, lo, hi, os.path.join(OUT_DIR, name))
    with open(os.path.join(OUT_DIR, "default.font"), "w") as f:
        f.write("# The default font: height and ascent, then a rune range per\n")
        f.write("# line -- low high subfont-file, all hex. ASCII is the baked\n")
        f.write("# table in sys/libfont and is not listed. GENERATED by\n")
        f.write("# tools/gensubfont.py.\n")
        f.write(f"{CELL_H:x} {ASCENT:x}\n")
        for lo, hi, name in RANGES:
            f.write(f"{lo:x} {hi:x} {name}\n")
    print(f"wrote {len(RANGES)} subfonts and default.font to {os.path.normpath(OUT_DIR)}")


if __name__ == "__main__":
    main()
